import {checkAlphabetLetter} from './checkLetter';

describe('Check Alphabet Letter', () => {
    it('Test', () => {
        expect(checkAlphabetLetter("a")).toBe(true);
        expect(checkAlphabetLetter("b")).toBe(true);
        expect(checkAlphabetLetter("c")).toBe(true);
        expect(checkAlphabetLetter("d")).toBe(true);
        expect(checkAlphabetLetter("e")).toBe(true);
        expect(checkAlphabetLetter("f")).toBe(true);
        expect(checkAlphabetLetter("g")).toBe(true);
        expect(checkAlphabetLetter("h")).toBe(true);
        expect(checkAlphabetLetter("i")).toBe(true);
        expect(checkAlphabetLetter("j")).toBe(true);
        expect(checkAlphabetLetter("k")).toBe(true);
        expect(checkAlphabetLetter("l")).toBe(true);
        expect(checkAlphabetLetter("m")).toBe(true);
        expect(checkAlphabetLetter("n")).toBe(true);
        expect(checkAlphabetLetter("o")).toBe(true);
        expect(checkAlphabetLetter("p")).toBe(true);
        expect(checkAlphabetLetter("q")).toBe(true);
        expect(checkAlphabetLetter("r")).toBe(true);
        expect(checkAlphabetLetter("s")).toBe(true);
        expect(checkAlphabetLetter("t")).toBe(true);
        expect(checkAlphabetLetter("u")).toBe(true);
        expect(checkAlphabetLetter("v")).toBe(true);
        expect(checkAlphabetLetter("w")).toBe(true);
        expect(checkAlphabetLetter("x")).toBe(true);
        expect(checkAlphabetLetter("z")).toBe(true);
        expect(checkAlphabetLetter("A")).toBe(true);
        expect(checkAlphabetLetter("B")).toBe(true);
        expect(checkAlphabetLetter("C")).toBe(true);
        expect(checkAlphabetLetter("D")).toBe(true);
        expect(checkAlphabetLetter("E")).toBe(true);
        expect(checkAlphabetLetter("F")).toBe(true);
        expect(checkAlphabetLetter("G")).toBe(true);
        expect(checkAlphabetLetter("H")).toBe(true);
        expect(checkAlphabetLetter("I")).toBe(true);
        expect(checkAlphabetLetter("J")).toBe(true);
        expect(checkAlphabetLetter("K")).toBe(true);
        expect(checkAlphabetLetter("L")).toBe(true);
        expect(checkAlphabetLetter("M")).toBe(true);
        expect(checkAlphabetLetter("N")).toBe(true);
        expect(checkAlphabetLetter("O")).toBe(true);
        expect(checkAlphabetLetter("P")).toBe(true);
        expect(checkAlphabetLetter("Q")).toBe(true);
        expect(checkAlphabetLetter("R")).toBe(true);
        expect(checkAlphabetLetter("S")).toBe(true);
        expect(checkAlphabetLetter("T")).toBe(true);
        expect(checkAlphabetLetter("U")).toBe(true);
        expect(checkAlphabetLetter("V")).toBe(true);
        expect(checkAlphabetLetter("W")).toBe(true);
        expect(checkAlphabetLetter("X")).toBe(true);
        expect(checkAlphabetLetter("Z")).toBe(true);
        expect(checkAlphabetLetter("y")).toBe(true);
        expect(checkAlphabetLetter("Y")).toBe(true);
        expect(checkAlphabetLetter("")).toBe(false);
        expect(checkAlphabetLetter(" ")).toBe(false);
        expect(checkAlphabetLetter("  ")).toBe(false);
        expect(checkAlphabetLetter("0")).toBe(false);
        expect(checkAlphabetLetter("1")).toBe(false);
        expect(checkAlphabetLetter("2")).toBe(false);
        expect(checkAlphabetLetter("3")).toBe(false);
        expect(checkAlphabetLetter("4")).toBe(false);
        expect(checkAlphabetLetter("5")).toBe(false);
        expect(checkAlphabetLetter("6")).toBe(false);
        expect(checkAlphabetLetter("7")).toBe(false);
        expect(checkAlphabetLetter("8")).toBe(false);
        expect(checkAlphabetLetter("9")).toBe(false);
        expect(checkAlphabetLetter("10")).toBe(false);
        expect(checkAlphabetLetter(" 1")).toBe(false);
        expect(checkAlphabetLetter(".")).toBe(false);
        expect(checkAlphabetLetter(",")).toBe(false);
        expect(checkAlphabetLetter(". ")).toBe(false);
        expect(checkAlphabetLetter(", ")).toBe(false);
        expect(checkAlphabetLetter(" . ")).toBe(false);
        expect(checkAlphabetLetter(" , ")).toBe(false);
        expect(checkAlphabetLetter(" 1 ")).toBe(false);
        expect(checkAlphabetLetter("null")).toBe(false);
        expect(checkAlphabetLetter("undefined")).toBe(false);

    });
});